---
name: "Audit"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * 1"
jobs:
  Audit:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: "actions/checkout@v4"
    - run: "sudo apt-get update"
    - run: "sudo apt-get install -y cargo make"
    - run: "make -f install.mk"
    - run: "make audit"
