---
name: "Audit"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * 1"
  workflow_dispatch:
jobs:
  Audit:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "dtolnay/rust-toolchain@stable"
      with:
        toolchain: "1.86.0"
    - name: "provision audit tools"
      run: "make -f install.mk crates"
    - run: "make audit"
