---
name: "Test"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
jobs:
  Test:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - run: "sudo apt-get update"
    - run: "sudo apt-get install -y cargo make"
    - run: "make -f install.mk"
    - run: "make test"
