---
name: "Test"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Test:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "dtolnay/rust-toolchain@stable"
      with:
        toolchain: "1.87.0"
    - name: "provision dev tools"
      run: "make -f install.mk -j 4"
    - run: "make test"
