---
name: "Test"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
jobs:
  Test:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "dtolnay/rust-toolchain@stable"
      with:
        toolchain: "1.86.0"
    - run: "make test"
